name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
  
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
  
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: UserManagement
          environment_name: UserManagement-env
          version_label: ${{ steps.version.outputs.version }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
